export const navLinks=[
    {
        id:"home",
        title:"Home",
    },
    {
        id:"services",
        title:"Services",
    },
    {
        id:"AboutUs",
        title:"AboutUs",
    },
    {
        id:"pricing",
        title:"Pricing",
    },
    {
        id:"menu",
        title:"Menu",
    },
    {
        id:"blog",
        title:"Blog",
    },
    {
        id:"contacts",
        title:"Contacts",
    },
]